name: Feature request
description: Suggest a feature
labels: ["C-feat", "S-needs-triage"]
title: "[Feature] "
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the feature has not already been requested in the issue tracker.
  - type: dropdown
    attributes:
      label: Component
      description: What crate is the feature for?
      multiple: true
      options:
        - consensus
        - genesis
        - protocol
        - registry
        - rpc
        - other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the feature you would like
      description:
        Please also describe your goals for the feature. What problems it solves, how it would be
        used, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context to the feature (like screenshots, resources)
