[package]
name = "maili-provider"
description = "Interface with an OP Stack blockchain"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
maili-rpc-types-engine = { workspace = true, features = ["serde"] }

# OP-Alloy
op-alloy-rpc-types-engine = { workspace = true, features = ["serde"] }

# Alloy
alloy-network.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true
alloy-primitives = { workspace = true, features = ["rlp", "serde"] }
alloy-rpc-types-engine = { workspace = true, features = ["serde"] }

# misc
async-trait.workspace = true

[dev-dependencies]
# `serde` must be explicitly enabled to test with `--no-default-features`
maili-protocol = { workspace = true, features = ["serde"] }
