[package]
name = "maili-rpc"
description = "Optimism RPC Client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
maili-protocol = { workspace = true, default-features = false, features = ["serde"] }
maili-common = { workspace = true, default-features = false, features = ["serde"] }

# OP-Alloy
op-alloy-rpc-types.workspace = true

# Alloy
alloy-eips.workspace = true
alloy-primitives.workspace = true

# rpc
jsonrpsee = { workspace = true, optional = true }
getrandom = { workspace = true, optional = true } # req for wasm32-unknown-unknown
serde.workspace = true

[features]
default = ["std", "jsonrpsee"]
std = [
    "maili-protocol/std",
    "maili-common/std",
    "op-alloy-rpc-types/std",
    "alloy-eips/std",
    "alloy-primitives/std",
]
jsonrpsee = [
    "dep:jsonrpsee",
    "dep:getrandom",
]
client = [
    "jsonrpsee",
    "jsonrpsee/client",
    "jsonrpsee/async-client",
]
