[package]
name = "maili-rpc"
description = "Optimism RPC API"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
maili-protocol = { workspace = true, optional = true, default-features = false, features = ["serde"] }
maili-common = { workspace = true, optional = true, default-features = false, features = ["serde"] }

# Alloy
alloy-eips = { workspace = true, features = ["serde"] }
alloy-primitives = { workspace = true, features = ["map", "rlp", "serde"] }

# rpc
jsonrpsee = { workspace = true, optional = true }
getrandom = { workspace = true, optional = true } # req for wasm32-unknown-unknown
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

[features]
default = ["std", "jsonrpsee"]
std = [
    "maili-protocol?/std",
    "maili-common?/std",
    "alloy-eips/std",
    "alloy-primitives/std",
]
jsonrpsee = [
    "dep:maili-common",
    "dep:maili-protocol",
    "dep:jsonrpsee",
    "dep:getrandom",
]
client = [
    "jsonrpsee",
    "jsonrpsee/client",
    "jsonrpsee/async-client",
]
