[package]
name = "maili-rpc"
description = "Optimism RPC Types and API"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
maili-protocol.workspace = true

# OP Alloy
op-alloy-rpc-types-engine.workspace = true

# Alloy
alloy-eips.workspace = true
alloy-primitives = { workspace = true, features = ["map", "rlp"] }

# Misc
derive_more = { workspace = true, default-features = false, features = ["display", "from"] }

# `serde`
serde = { workspace = true, optional = true }

# `jsonrpsee`
maili-genesis = { workspace = true, optional = true }
jsonrpsee = { workspace = true, optional = true }
getrandom = { workspace = true, optional = true } # req for wasm32-unknown-unknown

[dev-dependencies]
serde_json.workspace = true

[features]
default = ["std", "jsonrpsee"]
std = [
    "maili-protocol/std",
    "maili-genesis?/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "op-alloy-rpc-types-engine/std",
]
serde = [
    "dep:serde",
    "maili-protocol/serde",
    "maili-genesis?/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "op-alloy-rpc-types-engine/serde",
]
jsonrpsee = [
    "serde",
    "dep:maili-genesis",
    "dep:jsonrpsee",
    "dep:getrandom",
]
client = [
    "jsonrpsee",
    "jsonrpsee/client",
    "jsonrpsee/async-client",
]
