name: lint

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check crates correctly propagate features
  feature-propagation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: fetch deps
        run: |
          # Eagerly pull dependencies
          time cargo metadata --format-version=1 --locked > /dev/null
      - name: run zepter
        run: |
          cargo install zepter -f --locked
          zepter --version
          time zepter run check
