name: Publish

on:
  push:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  print-branch-name:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Print the branch name env variable
        run: echo "$BRANCH_NAME"
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
